### ISSUE TITLE
find items missing data in return

### ISSUE THREAD

**Issue by dwief-usgs** [DOI-USGS/sciencebasepy#10]
Noticed that the distributionLink was not returned when using sb.find_items.  Instead an empty list was returned.

![image](https://user-images.githubusercontent.com/18450000/83425496-08e3a480-a3eb-11ea-936f-af038950fca3.png)

Note for example one distributionLink should be returned:
https://www.sciencebase.gov/catalog/item/5e2b6bf9e4b0a79317d1824d?format=json

I'll try looking into this and seeing how often it occurs and/or if there are patterns causing this but I have seen some cases too that are returning the correct information.

**Comment by dwief-usgs** [comment]
from what I gather... this is occurring for any items that are pointing to services elsewhere.  a few other examples:
https://www.sciencebase.gov/catalog/item/5e2b701ee4b0a79317d1917f
https://www.sciencebase.gov/catalog/item/5373d13de4b0497061278c1e

In quick search through package this might not be something that can be fixed directly in sciencebasepy???

**Comment by jllong-usgs** [comment]
Sorry for the delay on this response. Add '"loadInstances": True' to your find_items parameters. distributionLinks is a very unique field, in that it is not indexed in elasticsearch, but  only created when an item is built from mongoDB. The find_items method returns the elasticsearch JSON. The loadInstances parameter tells ScienceBase to go ahead and build all of the items from their mongoDB instance instead.
