### ISSUE TITLE
Return Hidden Properties for Multiple Items

### ISSUE THREAD

**Issue by mlangseth** [DOI-USGS/sciencebasepy#2]
If I have a query to pull back multiple ScienceBase items, is it possible to have hidden properties for each item returned in a single call?

We store a unique identifier in hidden properties for items that were created using the ScienceBase Data Release Tool. I'd like to be able to run some statistics on items that were created using the tool, but I don't want to have thousands of SB calls to pull back this information.

For example:

query = {'filter': 'systemType=Data Release','fields':'contacts','max':1000,'sort':'title','order':'asc','offset':offset}
response = sb.find_items(query)

Is it possible to include hidden properties in the query?

**Comment by dignizio-usgs** [comment]
Documented for SB3 planning. Will discuss options for integrating something like this into SB2 depending on scale of effort, options with SB2 configuration, and timeline for migration to SB3 Search.

**Comment by dignizio-usgs** [comment]
An example of a query that would pull from both components (item + hidden properties) is described below.

The idea would be able to query for:

'systemType=DataRelease' (which comes from the item model) 
AND where 
the hidden properties has a value of type "SBDR_Tool_ID" present (which is in ancillary table)

Example item here:
https://www.sciencebase.gov/catalog/item/5b0b0625e4b0c39c93491961/hiddenProperties
