### ISSUE TITLE
Files associated with the ScienceBase item are not included in the item json (and sb.get_item_file_info(item_json) returns empty list)

### ISSUE THREAD

**Issue by wzell-usgs** [DOI-USGS/sciencebasepy#28]
Hi - thanks for your work on this repository. I've successfully used the library to create a new item on ScienceBase and upload files to that item (both on-premise files and cloud-hosted files).  I am attempting to view what files have already been uploaded to the item as well as update the metadata for some files (e.g., a file's 'title' attribute, which can be accessed via 'Edit Item'/'Files' - cf. 1st image pasted below).  However - the item JSON doesn't include any file information (cf. 2nd image pasted below).  Is this expected behavior? Thx.

![image](https://user-images.githubusercontent.com/16402586/176513064-fad7a878-2cd2-498b-8b5d-c2a238c0849d.png)

![image](https://user-images.githubusercontent.com/16402586/176514142-ae627560-20bd-4b20-a6f1-159ee49d2bfc.png)

**Comment by ennsk** [comment]
@wzell-usgs You should use the sb.get_item() method to get more information on the files within that item.  
```
item_json = sb.get_item('62bb9490d34e88efc5245d50')
```
