### ISSUE TITLE
How to perform spatial query with params?

### ISSUE THREAD

**Issue by philipbaileynar** [DOI-USGS/sciencebasepy#3]
How do I perform a spatial query using a bounding box please?

I would like to pull all National Elevation Data (NED) 1m items that overlap with a bounding box. Here's my attempt:

```python
import sciencebasepy

sb = sciencebasepy.SbSession()
result = sb.find_items({'spatialQuery':'{type:"envelope",coordinates:[[-104.775691,42.494826], [-99.85381,40.1184554]]}'})
```

But I'm getting back `Resource not found, or user does not have access` which makes me think that I have not formatted the query properly.

In the future I would like to enhance this with two improvements:

* Use an irregular bounding polygon instead of a simple rectangle
* Also apply a text filter to the search. So any items with the words "NED" **and** intersect with the bounding shape.

Any advice would be greatly appreciated! Thanks

**Comment by jllong-usgs** [comment]
You're close. Your filter should be:{'filter': 'spatialQuery={type:"envelope",coordinates:[[-104.775691,42.494826], [-99.85381,40.1184554]]}'}

There's a good example in https://github.com/usgs/sciencebasepy/blob/master/Searching%20ScienceBase%20with%20ScienceBasePy.ipynb
under the spatialQuery section. I'm not a big fan of how Github displays that notebook, but there are a lot of good examples in there.

**Comment by jllong-usgs** [comment]
Also, your query for "NED" would be {'q':'NED', 'filter', 'spatialQuery={type:"envelope",coordinates:[[-104.775691,42.494826], [-99.85381,40.1184554]]}'}

I'll see if I can come up with an example of how to search via polygon, I think that's possible.

**Comment by jllong-usgs** [comment]
For a polygon, the filter value would be something like this:
'spatialQuery={"type": polygon, "wkt": "POLYGON((-98.000000 30.000000,-81.000000 30.000000,-81.000000 40.000000,-98.000000 40.000000,-98.000000 30.000000))"}'

**Comment by philipbaileynar** [comment]
It's working! Thank you so much for the extremely fast response!
