### ISSUE TITLE
Login failing

### ISSUE THREAD

**Issue by nikmolnar** [DOI-USGS/sciencebasepy#31]
`SbSession.login` is currently raising an exception with the message "Login failed" for valid credentials. The problem seems to be that `https://my.usgs.gov/josso/signon/usernamePasswordLogin.do` is returning an HTML sign in form and is not setting the expected `JOSSO_SESSIONID` cookie. It does set cookies called `JSESSIONID` and `BNES_JSESSIONID`, so perhaps USGS has changed protocols and is no longer using JOSSO?

**Comment by nikmolnar** [comment]
This was due to an old version of the library. I can confirm this problem doesn't occur on `2.0.4`.

**Comment by dignizio-usgs** [comment]
After user follow up, issue is no longer presenting. Will close.
