### ISSUE TITLE
Get Items with Multiple Filters

### ISSUE THREAD

**Issue by philipbaileynar** [DOI-USGS/sciencebasepy#4]
I am trying to get items from Science base with the following parameters:

- Name includes the string ''USGS NED 1 arc-second''
- Type is "Citation"
- Tags include "IMG" and "Grid"
- Contributor is "U.S. Geological Survey"
- and bounding coordinates: [[-114.21, 42.25], [-112.69, 43.49]]

Thanks to your help (#3), I have the following parameters that do the name and bounding coordinates. But I can't figure out how to include multiple filters the way the Science Base advanced query URL encodes them.

```
{'q': 'USGS NED 1 arc-second', 'filter': 'spatialQuery={type:"envelope",coordinates:[[-114.21513407169732, 42.25073316889598], [-112.69624280217994, 43.498691924247616]]}'}
```

**Comment by jllong-usgs** [comment]
Filters can be numbered 0-9 (that's mentioned in the search ipython notebook take a look at that). I think a better way to get those products than by name would be to limit it to ancestors of the 1 Arc-second DEM item: 
```
    sbquery = {
        # An ancestor of the 1 arc-second DEM item
        'ancestors': '4f70aa71e4b058caae3f8de1',
        # Citation browse type
        'browseType': 'Citation',
        # Contains the tag Grid or IMG
        'filter0': 'tags=Grid',
        'filter1': 'tags=IMG',
        'conjunction': 'tags=OR',
        # In the given bounding box
        'filter2': 'spatialQuery={type:"envelope",coordinates:[[-114.21513407169732, 42.25073316889598], [-112.69624280217994, 43.498691924247616]]}'
    }

    result = sb.find_items(sbquery)
```
That query returns 15 items. I am not sure what you mean by Contributor, I'm not seeing any of the items with that contact type.

**Comment by philipbaileynar** [comment]
This was an immense help. It is working. THANK YOU!

The ancestor filter makes perfect sense and eliminates my fears of getting unintended items that third parties might have uploaded.
