### ISSUE TITLE
Migration to Login.gov

### ISSUE THREAD

**Issue by nikmolnar** [DOI-USGS/sciencebasepy#45]
I just received an email that all ScienceBase accounts will need to migrate to Login.gov. How will this affect login functionality for this library and are there plans in place to migrate? It seems like there's a short timeline for this, with the deadline for migration being July 15.

I noticed that Login.gov will require 2FA which adds an additional challenge, though I assume it would be possible to use a library such as [pyotp](https://github.com/pyauth/pyotp) to address this.

**Comment by dignizio-usgs** [comment]
@nikmolnar Thanks for the comment. We're trying to minimize impacts for API users. I'll respond with more details in an email.
