### ISSUE TITLE
login no longer allowing access

### ISSUE THREAD

**Issue by bclayton-usgs** [DOI-USGS/sciencebasepy#47]
It looks like ScienceBase just changed the login requirements and using `sb.login` or `sb.loginc` results in `Resource not found, or user does not have access` when trying to get an item.

**Comment by bclayton-usgs** [comment]
Issue was fixed, thanks.

**Comment by dignizio-usgs** [comment]
@bclayton-usgs  thanks for the note. We've temporarily reverted to our (soon to be retired) authentication approach. Please be aware that ScienceBase is in the process of implementing MFA (Multi Factor Authentication) for our login sequence, per Department guidance. As a result, there may be implications for API users and the Python and R libraries we maintain. We are working through options for an updated approach while trying to minimize impacts  to users with the changes in USGS Active Directory and updated DOI policies.
Please reach out to me directly or via sciencebase@usgs.gov for additional specifics as this evolves.
